# Generated by Django 2.2.10 on 2020-03-21 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_indexed_field_to_bookmark_model'),
        ('search', '0001_add_index_bookmark_modal'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBookmarkTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bookmark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_index_bookmark_task', to='core.Bookmark')),
            ],
            options={
                'db_table': 'index_bookmark_task',
            },
        ),
        migrations.DeleteModel(
            name='IndexBookmark',
        ),
        migrations.AddConstraint(
            model_name='indexbookmarktask',
            constraint=models.UniqueConstraint(fields=('bookmark',), name='uq_bookmark_id'),
        ),
    ]
