version: '3.7'
services:
  app:
    build:
      context: ./smart-bookmarks-django
    image: app-image
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=smart_bookmarks.settings
      - DB_NAME=smart-bookmarks-dev
      - DB_USER=dev
      - DB_PASSWORD=test123
      - DB_HOST=database
      - DB_PORT=5432
      - RABBITMQ_USER=dev
      - RABBITMQ_PASS=test123
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8000
    volumes:
      - ./smart-bookmarks-django:/app
    depends_on:
      - database
      - redis
  celery-beat:
#    build: .
    image: app-image
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=smart_bookmarks.settings
      - DB_NAME=smart-bookmarks-dev
      - DB_USER=dev
      - DB_PASSWORD=test123
      - DB_HOST=database
      - DB_PORT=5432
      - RABBITMQ_USER=dev
      - RABBITMQ_PASS=test123
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["/usr/bin/env", "celery", "--app=smart_bookmarks.celery:celery_app", "beat", "-l", "info"]
    volumes:
      - ./smart-bookmarks-django:/app
    depends_on:
      - database
      - rabbitmq
      - redis
  celery-worker-default:
    #    build: .
    image: app-image
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=smart_bookmarks.settings
      - DB_NAME=smart-bookmarks-dev
      - DB_USER=dev
      - DB_PASSWORD=test123
      - DB_HOST=database
      - DB_PORT=5432
      - RABBITMQ_USER=dev
      - RABBITMQ_PASS=test123
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["/usr/bin/env", "celery", "--app=smart_bookmarks.celery:celery_app", "worker", "-l", "info", "-Q", "default", "--concurrency=2", "-n", "worker.default@%h"]
    volumes:
      - ./smart-bookmarks-django:/app
    depends_on:
      - database
      - rabbitmq
      - redis
  celery-worker-priority:
    #    build: .
    image: app-image
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=smart_bookmarks.settings
      - DB_NAME=smart-bookmarks-dev
      - DB_USER=dev
      - DB_PASSWORD=test123
      - DB_HOST=database
      - DB_PORT=5432
      - RABBITMQ_USER=dev
      - RABBITMQ_PASS=test123
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["/usr/bin/env", "celery", "--app=smart_bookmarks.celery:celery_app", "worker", "-l", "info", "-Q", "priority", "--concurrency=4", "-n", "worker.priority@%h"]
    volumes:
      - ./smart-bookmarks-django:/app
    depends_on:
      - database
      - rabbitmq
      - redis
  rabbitmq:
    image: rabbitmq:3.8.2
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=test123
    ports:
      - 5672:5672
  nginx:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - app
  database:
    container_name: database
    restart: unless-stopped
    image: postgres:12
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=smart-bookmarks-dev
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: "redis:5"
    restart: unless-stopped
    ports:
      - 6379:6379
  flower:
#    image: mher/flower
#    environment:
#      - CELERY_BROKER_URL=amqp://dev:test123@rabbitmq:5672
#      - FLOWER_PORT=8888
#    ports:
#      - 8888:8888
    image: app-image
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=smart_bookmarks.settings
      - DB_NAME=smart-bookmarks-dev
      - DB_USER=dev
      - DB_PASSWORD=test123
      - DB_HOST=database
      - DB_PORT=5432
      - RABBITMQ_USER=dev
      - RABBITMQ_PASS=test123
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["/usr/bin/env", "celery", "flower", "-A", "smart_bookmarks.celery:celery_app"]
    ports:
      - 5555:5555
    volumes:
      - ./smart-bookmarks-django:/app
    depends_on:
      - rabbitmq

volumes:
  dbdata:
