# Generated by Django 2.2.10 on 2020-03-07 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_page_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapePage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bookmark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_scrape_page', to='core.Bookmark')),
            ],
            options={
                'db_table': 'scrape_page',
            },
        ),
    ]
