# Generated by Django 2.2.10 on 2020-02-29 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookmarks', '0002_add_page_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapePageTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bookmark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_page_tasks', to='bookmarks.Bookmark')),
            ],
            options={
                'db_table': 'scrape_page_task',
            },
        ),
    ]
