# Generated by Django 2.2.10 on 2020-03-21 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_indexed_field_to_bookmark_model"),
        ("scrapers", "0001_add_scrape_page_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapePageTask",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "bookmark",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_scrape_page_task",
                        to="core.Bookmark",
                    ),
                ),
            ],
            options={"db_table": "scrape_page_task"},
        ),
        migrations.DeleteModel(name="ScrapePage",),
    ]
