# Generated by Django 2.2.10 on 2020-03-21 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_indexed_field_to_bookmark_model'),
        ('scrapers', '0002_replace_scrape_page_with_scrape_page_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapePageError',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=1024)),
                ('bookmark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_scrape_page_error', to='core.Bookmark')),
            ],
            options={
                'db_table': 'scrape_page_error',
            },
        ),
    ]
