# Generated by Django 2.2.10 on 2020-03-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0003_add_scrape_page_error_model"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="scrapepagetask",
            constraint=models.UniqueConstraint(
                fields=("bookmark",), name="uq_scrape_page_task_bookmark_id"
            ),
        ),
    ]
