# Generated by Django 2.2.10 on 2020-03-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_require_title_description_source_in_page_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='indexed',
            field=models.DateTimeField(null=True),
        ),
    ]
